project_id = "nyouhqyenazoocxiomgb"

# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
name = "lovable-project"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
image_transformation = true
image_resize = true

[auth]
enabled = true
port = 54329
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
email_confirm = false

[functions.fetch-news]
verify_jwt = false

[functions.ai-recommendations]
verify_jwt = false

[functions.enhanced-news-aggregator]
verify_jwt = false

[functions.ai-personalized-recommendations]
verify_jwt = false

[functions.enhanced-content-analyzer]
verify_jwt = false

[functions.multi-source-news-aggregator]
verify_jwt = false

[functions.generate-dynamic-articles]
verify_jwt = false

[functions.process-user-feedback]
verify_jwt = false

[functions.ai-content-analysis]
verify_jwt = false

[functions.firecrawl-news-aggregator]
verify_jwt = false

[functions.cybotic-news-system]
verify_jwt = false

[functions.lovable-reel-transformer]
verify_jwt = false

[functions.lovable-content-refiner]
verify_jwt = false

[functions.auto-news-refresh]
verify_jwt = false

[functions.enhanced-data-sync]
verify_jwt = false

[functions.mood-processor]
verify_jwt = false

[edge_runtime]
policy = "per_function"
inspector_port = 54330

[analytics]
enabled = false

[dashboard]
port = 54323