// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nyouhqyenazoocxiomgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55b3VocXllbmF6b29jeGlvbWdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDUwMDIsImV4cCI6MjA2OTk4MTAwMn0.LjDlrJGjJK9RxkRUhPGvlj8WbZIxYwv090orTI7-ZeY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});